FORMAT: 1A
HOST: https://snowman-challange-api.herokuapp.com

# Snowman Backend Challenge

That is a simple API allowing users to view tourist spots and vote in them.

# Data Structures

## User (object)
+ id
+ username
+ password

## UserRegister (object)
+ username
+ password


## TouristSpot (object)
+ id
+ name
+ gps
+ id_category

# Category (object)
+ id
+ name


# Group API Endpoints

## User [/users]
### User List [GET]
+ Response 200 (application/json)

    + Attributes (array[User])


### User Registry [POST /user/register]
+ Request

    + Headers
    
            Content-Type: application/json

    + Body

            {
                "username":"Usuario",
                "password":"54321"
            }

+ Response 201 (application/json)

    + Attributes (array[UserRegister])
    
    
### User Acess Token [POST /auth]
+ Request

    + Headers
    
            Content-Type: application/json

    + Body

            {
                "username":"Lucas",
                "password":"qwer"
            }

+ Response 201 (application/json)

    + Attributes (array[UserRegister])
    
    

## Tourist Spot [/tourist-spot]
### Tourist Spot List [GET]
+ Response 200 (application/json)

    + Attributes (array[TouristSpot])
    


### Tourist Spot Registry [POST /tourist-spot]
+ Request

    + Headers
    
            Content-Type: application/json
    
            Authorization: JWT <paste_here_the_acess_token>

    + Body

            {
                "name":"Nice Place",
                "gps":"(lati, long)",
                "id_category": 1
            }

+ Response 201 (application/json)

    + Attributes (array[TouristSpot])
    



## Category [/category]
### Category List [GET]
+ Response 200 (application/json)

    + Attributes (array[Category])


### Category Registry [POST /category]
+ Request

    + Headers
    
            Content-Type: application/json

    + Body

            {
                "name":"Beach"
            }

+ Response 201 (application/json)

    + Attributes (array[Category])